# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios,'15.1'

# use_modular_headers!

# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end



# target 'VideoApp' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   pod 'Firebase', '>= 10.18.0', :modular_headers => true
#   pod 'FirebaseCore', '>= 10.18.0', :modular_headers => true
#   pod 'FirebaseAuth', '>= 10.18.0', :modular_headers => true
#   pod 'GoogleUtilities', :modular_headers => true

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0' # or '14.0' if you're targeting lower

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks!
end

use_frameworks!
use_modular_headers!

target 'VideoApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Add Firebase pods here
  # pod 'FirebaseAuth'
  # pod 'FirebaseCore'

  pod 'FirebaseCore', '>= 10.18.0', :modular_headers => true
  pod 'FirebaseAuth', '>= 10.18.0', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  # Add more Firebase pods as needed
  # pod 'FirebaseFirestore'
  # pod 'FirebaseAnalytics'
  # pod 'FirebaseMessaging'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # 💡 Optional: force deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end

